config/routes.rb
Rails.application.routes.draw do

  root "users#home"
  resources :tasks
  resources :teams
  devise_for :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :tasks, dependent: :destroy
end

app/models/team_user.rb
class TeamUser < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_and_belongs_to_many :teams

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = current_user.tasks.all
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  def show
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @task.save
        # Twilio messaging--move later
        message = "Task Chief here! You have more work to do! '#{@task.title}' was just added to your tasks."
        TwilioTextMessenger.new(message).call
        format.html { redirect_to root_path, notice: 'Task was successfully created.' }
        format.json { render :root, status: :created, location: root_path }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to root_path, notice: 'Task was successfully updated.' }
        format.json { render :root, status: :ok, location: root_path }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :interval, :task_id)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]
  before_action :set_user
  before_action :set_user_teams

  # GET /teams
  # GET /teams.json
  def index
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @team.save
        format.html { redirect_to root_path, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: root_path }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to root_path, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: root_path }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    def set_user
      @user = User.find(current_user.id)
    end
    # adds current_user's teams to @user.teams
    def set_user_teams
      @user.teams << Team.where(user_id: current_user.id)
      @user.teams = @user.teams.distinct
      @teams = @user.teams
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def home
      @teams = Team.where(user_id: current_user.id)
      @tasks = Task.where(user_id: current_user.id)
      @tasks_all = Task.all
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teams.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TaskHive
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    / %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
    %nav.navbar.navbar-expand-lg.navbar-dark
      .navbar-brand
        = link_to "Task Hub", root_path
      %span.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNav", "data-toggle" => "collapse"}
        %span.navbar-toggler-icon
      #navbarNav.collapse.navbar-collapse
        %ul.navbar-nav
          %li.nav-item
            .nav-link
              = link_to "Teams", teams_path
          %li.nav-item
            .nav-link
              = link_to "Tasks", tasks_path
          %li.nav-item
            .nav-link
              = link_to "Sign Out", destroy_user_session_path, method: :delete
    / alerts
    - if flash[:notice]
      .alert.alert-success{role: "alert"}
        = flash[:notice]
    = yield

app/views/tasks/_form.html.haml
= form_for @task do |f|
  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      %ul
        - @task.errors.full_messages.each do |message|
          %li= message
  = f.label(:title, "Task Title:")
  = f.text_field(:title)

  = f.label(:interval, "How many days per week must this task be done? (1-7):")
  = f.text_field(:interval)

  = f.select :team_id, options_from_collection_for_select(current_user.teams, :id, :name)
  .actions
    = f.submit 'Save'

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', @task
\|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%h1 Listing tasks

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @tasks.each do |task|
      %h5= task.title
      %tr
        %td= link_to 'Show', task
        %td= link_to 'Edit', edit_task_path(task)
        %td= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', root_path

app/views/tasks/show.html.haml
%p= @task.title
%p= @task.interval
%p= @task.user_id
%p= User.find(@task.user_id).email

app/views/users/_task_list.html.haml
%ul.list-team
  - @tasks.each do |task|
    / this should be a button
    = link_to id: "task-card-expand" do
      %li.list-team-item{:id => "#{task.id}"}
        .row
          .col-3.task-team-name
            %h5= task.team.name
          .col-7.list-item-title
            = task.title
          .col-2.list-item-triangle
            = image_tag "https://i.imgur.com/uLlPUfM.png", id: "carrot#{task.id}"
    .list-expanded{style: "display:none", id: "list-expanded#{task.id}"}
      %h5 Workers 2
      %h5 Frequency:
      = task.interval

app/views/users/_team_list.html.haml
%ul.list-team
  - @teams.each do |team|
    %li.list-team-item
      .row
        .list-item-title
          = team.name

app/views/users/home.html.haml
/ New Task | Manage Teams Button Section
.button-section
  .container
    .row
      .col-6
        .btn.btn-light.col-12
          = link_to "New Task", new_task_path, class: "btn"
      .col-6
        .btn.btn-light.col-12
          = link_to "New Team", teams_path, class: "btn"
    / Team and Task tabs and lists
.team-task-list
  .container
    .tab-header
      .row
        .col-6#show_tasks
          %h1= link_to "Tasks"
        .col-6#show_teams
          %h1= link_to "Teams"
    .list-content
      .col-12.item-list#task_list
        = render "task_list"
      .col-12.item-list#team_list{:style => "display:none"}
        = render "team_list"